import anthropic
from llms.llm_interface import LLMInterface

class Claude_LLM(LLMInterface):
    
    def __init__(self, api_key: str):
        """
        Initialize the Claude LLM client with the provided API key.
        
        :param api_key: API key for authenticating with the Claude API.
        """
        self.api_key = api_key
        self.client = anthropic.Anthropic(api_key=api_key)
    
    def generate_response(self, prompt: str) -> str:
        """
        Generate a response from the Claude LLM based on the provided prompt.
        
        :param prompt: The input prompt for which the LLM should generate a response.
        :return: The response content generated by the Claude LLM.
        """
        message = self.client.messages.create(
            model="claude-3-5-sonnet-20240620",
            max_tokens=1024,
            messages=[
                {"role": "user", "content": prompt}
            ]
        )
        return message.content
    
    def configure(self, api_key: str):
        """
        Reconfigure the LLM with a new API key.
        
        :param api_key: New API key for authenticating with the Claude API.
        """
        self.api_key = api_key
        self.client = anthropic.Anthropic(api_key=api_key)
