from langchain import HuggingFaceHub, LLMChain
from langchain.prompts import PromptTemplate

from llms.llm_interface import LLMInterface

class CustomLLM(LLMInterface):
    """
    A class to interface with Hugging Face's language model API using a custom LLM chain.

    Inherits from
    --------------
    LLMInterface

    Methods
    -------
    generate_response(prompt: str) -> str
        Generates a response to the given prompt using Hugging Face's API.
    configure(api_key: str)
        Configures the API key for accessing Hugging Face's API.
    """
    
    def __init__(self, repo: str, prompt_template: str):
        """
        Initializes the CustomLLMChain with the provided repository and prompt template.

        Parameters
        ----------
        repo : str
            The Hugging Face repository to use.
        prompt_template : str
            The prompt template to use for generating responses.
        """
        self.repo = repo
        self.prompt_template = prompt_template
        self.llm = HuggingFaceHub(repo=self.repo)
        self.prompt = PromptTemplate(
            input_variables=['question'],
            template=self.prompt_template
        )
        self.chain = LLMChain(prompt=self.prompt, llm=self.llm, verbose=True)
    
    def generate_response(self, prompt: str) -> str:
        """
        Generates a response to the given prompt using Hugging Face's API.

        Parameters
        ----------
        prompt : str
            The prompt or query to be sent to Hugging Face's API.

        Returns
        -------
        str
            The response generated by Hugging Face's API.
        """
        response = self.chain.run(question=prompt)
        return response
    
    def configure(self, api_key: str):
        """
        Configure the API key for Hugging Face's API.

        Parameters
        ----------
        api_key : str
            The API key to be used for authenticating with Hugging Face's API.
        """
        # Note: Hugging Face API keys might be set globally or via a different method.
        # This implementation may not be required if the API key is not directly used in the client.
        pass
