from abc import ABC, abstractmethod

class LLMInterface(ABC):
    """
    Abstract base class for language model interfaces.

    Methods
    -------
    generate_response(prompt: str) -> str
        Abstract method to generate a response based on the given prompt.
    configure(api_key: str)
        Abstract method to configure the API key for the model.
    """
    
    @abstractmethod
    def generate_response(self, prompt: str) -> str:
        """
        Generates a response to the given prompt using the LLM.

        Parameters
        ----------
        prompt : str
            The prompt or query to be sent to the LLM.

        Returns
        -------
        str
            The response generated by the LLM.
        """
        pass
    
    @abstractmethod
    def configure(self, api_key: str):
        """
        Configures the API key for accessing the LLM.

        Parameters
        ----------
        api_key : str
            The API key to be used for authenticating with the LLM.
        """
        pass
