from openai import OpenAI
from llms.llm_interface import LLMInterface

class OpenAI_LLM(LLMInterface):
    """
    A class to interface with OpenAI's language model API.

    Inherits from
    --------------
    LLMInterface

    Methods
    -------
    generate_response(prompt: str) -> str
        Generates a response to the given prompt using OpenAI's API.
    configure(api_key: str)
        Configures the API key for accessing OpenAI's API.
    """
    
    def __init__(self, api_key: str):
        """
        Initializes the OpenAI_LLM with the provided API key and sets it for the OpenAI client.

        Parameters
        ----------
        api_key : str
            The API key used for authenticating with OpenAI's API.
        """
        self.api_key = api_key
        self.client = OpenAI(api_key=self.api_key)
    
    def generate_response(self, prompt: str) -> str:
        """
        Generates a response to the given prompt using OpenAI's API.

        Parameters
        ----------
        prompt : str
            The prompt or query to be sent to OpenAI's API.

        Returns
        -------
        str
            The response generated by OpenAI's API.
        """
        chat_completion = self.client.chat.completions.create(
            model="gpt-4o-mini",  # Specify the desired model
            messages=[{"role": "user", "content": prompt}]
        )
        return chat_completion.choices[0].message["content"].strip()
    
    def configure(self, api_key: str):
        """
        Updates the API key for accessing OpenAI's API and sets it for the OpenAI client.

        Parameters
        ----------
        api_key : str
            The new API key to be used for authenticating with OpenAI's API.
        """
        self.api_key = api_key
        self.client = OpenAI(api_key=self.api_key)
